# Starts Gnome GMD on boot
# exec ck-launch-session gnome-session

# Starts urxvt daemon
urxvtd -q -o -f

# Active Numlock on boot, requires numlockx
numlockx &

# Starts i3 tile window manager
exec i3

# Load custom fonts (Terminus)
xset +fp /usr/share/fonts/local
xset fp rehash

# Disable system beep
xset -b

# Start Dropbox daemon
dropboxd
