[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# Set additional configs for git
source /usr/share/git/completion/git-completion.bash
source /usr/share/git/completion/git-prompt.sh

# Add Dart bins to PATH
PATH=$PATH:~/programs/dart/dart-sdk/bin

for file in ~/.{extra,bash_prompt,exports,bash_aliases,functions}; do
  [ -r "$file" ] && source "$file"
done
unset file
PATH="/usr/local/heroku/bin:$PATH"
