alias vi='vim'

#Shell
alias ls='ls --color'

#Git
alias gs='git status'
alias gb='git branch'
alias gp='git pull'
alias gpp='git push'
alias gcm='git checkout master'
alias gcp='git checkout production'
alias gfr='git fetch && git rebase'
alias gdc='git diff --cached'

#Projects
alias rp='cd ~/code/replaypoker'
alias productionx='bundle exec rake production deploy'
alias poker='rails runner "RP2Server.start(1)"'

#Transmission
alias pirateon='sudo systemctl start transmission.service'
alias pirateoff='sudo systemctl stop transmission.service'

#Pacman
alias update='sudo pacman -Syyu'

#Dart
alias dartium="DART_FLAGS='--enable_type_checks --enable_asserts' ~/bin/dartium/chrome"
