[ -n "$PS1" ] && source ~/.bash_profile

export EDITOR=vim

# Start ssh-agent
eval $(keychain --eval --agents ssh -Q --quiet id_rsa)

# Starts tmux
if [[ ! $TERM =~ screen ]]; then
  exec tmux
fi

# Mute terminal beeps
xset b off >&/dev/null

# Bash history across tmux sessions
# Appends cmd to bash history and reload it
export PROMPT_COMMAND="history -a; history -n"

# EC2 Commands
source /home/luiz/work/replaypoker/ec2/env
export JAVA_HOME=/opt/java/jre

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
