# Load RVM into a shell session *as a function*
[[ -s "/home/luiz/.rvm/scripts/rvm" ]] && source "/home/luiz/.rvm/scripts/rvm"

# Check if there is support for 256 colors
export TERM=screen-256color

# Show git branch in the prompt if available
source /etc/bash_completion.d/git
PS1='\w$(__git_ps1 "[%s]")> '

# Tmuxinator load path
[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator

# Start ssh-agent
eval $(keychain --eval --agents ssh -Q --quiet id_rsa)

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
